version: '3.8'

services:
  api:
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    depends_on:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: Minecraft4Life
      MYSQL_HOST: mysql
    restart: always


  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Minecraft4Life
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8090:80
    environment:
      MYSQL_ROOT_PASSWORD: Minecraft4Life
      PMA_HOST: mysql
    restart: always


volumes:
  db_data:
